services:
  tg-music-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: tg-music-bot
    environment:
      BOT_TOKEN_PROD: ${BOT_TOKEN_PROD}
      BOT_TOKEN_DEV: ${BOT_TOKEN_DEV}
      KATE_TOKEN: ${KATE_TOKEN}
      KATE_USER_AGENT: ${KATE_USER_AGENT}
      MUSIXMATCH_TOKEN: ${MUSIXMATCH_TOKEN}
      YOUTUBE_TOKEN: ${YOUTUBE_TOKEN}
    networks:
      - tg-bot-network
    volumes:
    - ./logs:/home/node/app/logs

networks:
  tg-bot-network:
    driver: bridge

volumes:
  logs: