services:
  tg-music-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: tg-music-bot
    env_file:
      - .env
    networks:
      - tg-bot-network

networks:
  tg-bot-network:
    driver: bridge
