services:
  tg-music-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: tg-music-bot
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    networks:
      - tg-bot-network
    volumes:
    - ./logs:/home/node/app/logs

networks:
  tg-bot-network:
    driver: bridge

volumes:
  logs: